version: "2"
linters:
  enable:
    - gosec
    - misspell
  disable:
    - goconst
    - godot
    - nestif
    - nolintlint
    - revive
  settings:
    govet:
      enable:
        - assign
        - atomic
        - bools
        - buildtag
        - cgocall
        - composites
        - copylocks
        - httpresponse
        - loopclosure
        - lostcancel
        - nilfunc
        - printf
        - shift
        - stdmethods
        - structtag
        - tests
        - unmarshal
        - unreachable
        - unsafeptr
        - unusedresult
      disable:
        - shadow
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: G101
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
